version: "2" # required to adjust maintainability checks

checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: false
  method-complexity:
    enabled: true
    config:
      threshold: 7
  method-count:
    enabled: false
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.

#plugins:
#  eslint:
#     enabled: true
#     channel: "eslint-6"
#  rubocop:
#     enabled: true
#     channel: "rubocop-0-79"

exclude_patterns:
  - "config/"
  - "db/"
  - "**/node_modules/"
  - "**/spec/"
  - "**/vendor/"
  - "**/admin/"
  - '**/services/xlsx_export/'
  - '**/services/csv_export/'
  - '**/services/csv_import/'
  - '**/models/clockwork.rb'
  - 'helpers/sitemap_helper.rb'
  - 'babel.config.js'
  - 'services/sitemap_generator.rb'
  - 'services/diagnosis_creation/create_automatic_diagnosis.rb'
