require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/migrate/20170420210630_devise_create_users.rb'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'node_modules/**/*'

Metrics/MethodLength:
  Exclude:
    - 'app/helpers/diagnosis_helper.rb' # TODO: Remove

Metrics/LineLength:
  Max: 160

Metrics/BlockLength:
  Max: 100

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Max: 7