---
openapi: 3.0.1
info:
  title: API Place des Entreprises V1
  description: "API destinée aux partenaires de Place des Entreprises et leur permettant
    d’interagir avec le service. \n\rSi vous souhaitez un accès, prenez-contact avec
    nous : nous étudierons votre demande et vous fournirons un token d’accès, le cas
    échéant."
  version: 1.0.0
  contact:
    name: Équipe technique
    email: tech@place-des-entreprises.beta.gouv.fr
paths:
  "/api/v1/landings":
    get:
      summary: Liste des pages formulaires
      tags:
      - Landings
      description: Affiche toutes les pages formulaires pour l'organisation authentifiée
      responses:
        '200':
          description: ok
          content:
            application/json:
              examples:
                test_example:
                  value:
                    data:
                    - id: 82
                      title: DINUM recrutement
                      slug: dinum-recrutement
                      partner_url: https://www.example.com/aides
                      iframe_category: integral
                      landing_themes:
                      - id: 139
                        title: matrix viral vortals
                        page_title: 
                        slug: lttempora1
                        description: At dolore sequi. Voluptatem labore facilis. Iure
                          magnam dolorem.
                        meta_title: 
                        meta_description: 
                        created_at: '2022-08-26T16:29:47.245+02:00'
                        updated_at: '2022-08-26T16:29:47.245+02:00'
                        archived_at: 
                      - id: 140
                        title: e-enable intuitive web services
                        page_title: 
                        slug: ltaccusantium4
                        description: Non odio consequatur. Consectetur dolor fugiat.
                          In doloremque dolores.
                        meta_title: 
                        meta_description: 
                        created_at: '2022-08-26T16:29:47.366+02:00'
                        updated_at: '2022-08-26T16:29:47.366+02:00'
                        archived_at: 
                    metadata:
                      total_results: 1
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/landing"
                  metadata:
                    type: object
                    properties:
                      total_results:
                        type: integer
                        description: Nombre de pages formulaires pour l’organisation
                          authentifiée.
        '404':
          description: Mauvais token
          content:
            application/json:
              examples:
                test_example:
                  value:
                    errors:
                    - source: Token d’API
                      message: n’existe pas ou est invalide
              schema:
                errors:
                  type: array
                  items:
                    "$ref": "#/components/schemas/error"
  "/api/v1/landings/search":
    get:
      summary: Recherche d’une page formulaire à partir de l’url de sa page d’appel
      tags:
      - Landings
      description: Afin de pouvoir tracer et quantifier les appels, nous enregistrons
        les url des pages des sites partenaires depuis lesquelles l’API est appelé.
        Ainsi, pour retrouver la page formulaire devant figurer à l’url XX, vous pouvez
        faire une recherche via cette url.
      parameters:
      - name: url
        in: query
        description: url de la page qui appelle l’API
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Page formulaire trouvée
          content:
            application/json:
              examples:
                test_example:
                  value:
                    data:
                      id: 85
                      title: DINUM recrutement
                      slug: dinum-recrutement
                      partner_url: https://www.example.com/aides
                      iframe_category: integral
                      landing_themes:
                      - id: 143
                        title: brand B2B networks
                        page_title: 
                        slug: ltcumque13
                        description: Ab autem rerum. Est voluptatem ab. Praesentium
                          vitae dolorum.
                        meta_title: 
                        meta_description: 
                        created_at: '2022-08-26T16:29:47.877+02:00'
                        updated_at: '2022-08-26T16:29:47.877+02:00'
                        archived_at: 
                      - id: 144
                        title: orchestrate frictionless deliverables
                        page_title: 
                        slug: ltminima16
                        description: Maiores dignissimos recusandae. Et voluptates
                          et. Et porro quibusdam.
                        meta_title: 
                        meta_description: 
                        created_at: '2022-08-26T16:29:47.948+02:00'
                        updated_at: '2022-08-26T16:29:47.948+02:00'
                        archived_at: 
                    metadata:
                      total_themes: 2
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/landing"
                  metadata:
                    type: object
                    properties:
                      total_themes:
                        type: integer
                        description: Nombre de thèmes liée à la page formulaire.
        '404':
          description: Page formulaire inconnue
          content:
            application/json:
              examples:
                test_example:
                  value:
                    errors:
                    - source: Landing
                      message: n’existe pas ou est invalide
              schema:
                errors:
                  type: array
                  items:
                    "$ref": "#/components/schemas/error"
        '400':
          description: Paramètres vides
          content:
            application/json:
              examples:
                test_example:
                  value:
                    errors:
                    - source: paramètres de requête
                      message: malformés ou inconnus
              schema:
                errors:
                  type: array
                  items:
                    "$ref": "#/components/schemas/error"
  "/api/v1/landings/{id}":
    get:
      summary: Page formulaire
      tags:
      - Landings
      description: Affiche le détail d’une page formulaire
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Page formulaire trouvée
          content:
            application/json:
              examples:
                test_example:
                  value:
                    data:
                      id: 88
                      title: DINUM recrutement
                      slug: dinum-recrutement
                      partner_url: https://www.example.com/aides
                      iframe_category: integral
                      landing_themes:
                      - id: 149
                        title: target interactive technologies
                        page_title: 
                        slug: ltporro31
                        description: Reiciendis rerum aut. Voluptatem dolores iusto.
                          Dolores consequatur minus.
                        meta_title: 
                        meta_description: 
                        created_at: '2022-08-26T16:29:48.497+02:00'
                        updated_at: '2022-08-26T16:29:48.497+02:00'
                        archived_at: 
                      - id: 150
                        title: grow frictionless technologies
                        page_title: 
                        slug: ltconsequatur34
                        description: Modi omnis eligendi. Et voluptatem voluptates.
                          Voluptas quod sint.
                        meta_title: 
                        meta_description: 
                        created_at: '2022-08-26T16:29:48.553+02:00'
                        updated_at: '2022-08-26T16:29:48.553+02:00'
                        archived_at: 
                    metadata:
                      total_themes: 2
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/landing"
                  metadata:
                    type: object
                    properties:
                      total_themes:
                        type: integer
                        description: Nombre de thèmes liée à la page formulaire.
servers:
- url: https://place-des-entreprises.beta.gouv.fr
- url: https://reso-staging.osc-fr1.scalingo.io
components:
  schemas:
    landing:
      type: object
      properties:
        id:
          type: integer
        iframe_category:
          type: string
        title:
          type: string
        slug:
          type: string
        partner_url:
          type: string
        landing_themes:
          type: array
          items:
            "$ref": "#/components/schemas/landing_theme"
      required:
      - id
      - title
      - partner_url
    landing_theme:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        slug:
          type: string
        landing_subjects:
          type: array
      required:
      - id
      - title
    error:
      type: object
      properties:
        source:
          type: string
        message:
          type: string
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      description: Le jeton vous est fourni après étude de votre demande par Place
        des Entreprises
security:
- bearer_auth: []
