export const REQUEST_IN_PROGRESS = 'REQUEST_IN_PROGRESS'
export const FORM_ERROR_TYPE = 'FORM_ERROR_TYPE'
export const SIRET = 'SIRET'
export const SIREN = 'SIREN'
export const COMPANIES = 'COMPANIES'
export const COMPANY_DATA = 'COMPANY_DATA'
