default: &default
  adapter: postgresql
  encoding: unicode
  pool: 100
  variables:
    statement_timeout: 30000

development:
  <<: *default
  database: place-des-entreprises-development
  host: localhost
  username: postgres
  password: postgres

test:
  <<: *default
  database: place-des-entreprises-test
  host: localhost
  username: postgres
  password: postgres

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *default
    database: app_production_cache
    migrations_paths: db/cache_migrate
