# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks

# The "main" locale.
base_locale: fr
## All available locales are inferred from the data by default. Alternatively, specify them explicitly:
# locales: [es, fr]
## Reporting locale, default: en. Available: en, ru.
# internal_locale: en

# Read and write translations.
data:
  ## Translations are read from the file system. Supported format: YAML, JSON.
  ## Provide a custom adapter:
  # adapter: I18n::Tasks::Data::FileSystem

  # Locale files or `File.find` patterns where translations are read from:
  read:
    - config/locales/**/*.%{locale}.yml
    - config/locales/%{locale}.yml
    ## Another gem (replace %#= with %=):
    # - "<%#= %x[bundle show vagrant].chomp %>/templates/locales/%{locale}.yml"

  # Locale files to write new keys to, based on a list of key pattern => file rules. Matched from top to bottom:
  # `i18n-tasks normalize -p` will force move the keys according to these rules
  write:
    # For example, write devise and simple form keys to their respective files:
    - ['{categories_juridiques}.*', 'config/locales/\1.%{locale}.yml']
    - ['{active_admin, activerecord, archivable, attributes}.*', 'config/locales/models.%{locale}.yml']
    - ['{about, companies, conseillers, devise, diagnoses, layouts, mailers, needs, solicitations, stats}.*', 'config/locales/views.%{locale}.yml']
    # Catch-all default:
    - config/locales/%{locale}.yml

  ## Specify the router (see Readme for details). Valid values: conservative_router, pattern_router, or a custom class.
  # router: convervative_router

  yaml:
    write:
      # do not wrap lines at 80 characters
      line_width: -1

  ## Pretty-print JSON:
  # json:
  #   write:
  #     indent: '  '
  #     space: ' '
  #     object_nl: "\n"
  #     array_nl: "\n"

# Find translate calls
search:
  ## Paths or `File.find` patterns to search in:
  # paths:
  #  - app/

  ## Root directories for relative keys resolution.
  # relative_roots:
  #   - app/controllers
  #   - app/helpers
  #   - app/mailers
  #   - app/presenters
  #   - app/views

  ## Files or `File.fnmatch` patterns to exclude from search. Some files are always excluded regardless of this setting:
  ##   %w(*.jpg *.png *.gif *.svg *.ico *.eot *.otf *.ttf *.woff *.woff2 *.pdf *.css *.sass *.scss *.less *.yml *.json)
  exclude:
    - app/assets/images
    - app/assets/fonts

  ## Alternatively, the only files or `File.fnmatch patterns` to search in `paths`:
  ## If specified, this settings takes priority over `exclude`, but `exclude` still applies.
  # include: ["*.rb", "*.html.slim"]

  ## Default scanner finds t() and I18n.t() calls.
  # scanner: I18n::Tasks::Scanners::PatternWithScopeScanner

## Google Translate
# translation:
#   # Get an API key and set billing info at https://code.google.com/apis/console to use Google Translate
#   api_key: "AbC-dEf5"

## Do not consider these keys missing:
ignore_missing:
# ignore_missing:
# - 'errors.messages.{accepted,blank,invalid,too_short,too_long}'
# - '{devise,simple_form}.*'

## Consider these keys used:
ignore_unused:
  - 'devise.*'
  - 'errors.messages.*'
  - 'activerecord.*'
  - 'active_admin.scopes.*'
  - 'active_admin.flag.*'
  - 'active_admin.move'
  - 'attributes.*'
  - 'department_codes_to_libelles.*'
  - 'department_code_to_region_code.*'
  - 'flash.actions.*'
  - 'landings.new_solicitation_form.attributes.*'
  - 'stats.stats_table.*'
  - 'stats.series.*'
  - 'categories_juridiques.*'
  - 'code_to_range.*'
  - 'simple_effectif.*'
  - 'codes_effectif.*'
  - 'naf_libelle_a10.*'
  - 'naf_libelle_level2.*'
  - 'naf_level2_to_naf_a10.*'
  - 'regions_codes_to_libelles.*'
  - 'regions_codes_to_slugs.*'
  - 'regions_slugs_to_codes.*'
  - 'faq.*'
  - 'prefill_feedbacks.*'
  - '{date,datetime,errors,helpers,number,support,time}.*'
  - 'solicitation.provenance_categories.*'
  - 'password.missing_elements.*'
  - 'antenne_stats_exporter.*'
  - 'reminders.needs.scopes.mark_done.*'
# - '{devise,kaminari,will_paginate}.*'
# - 'simple_form.{yes,no}'
# - 'simple_form.{placeholders,hints,labels}.*'
# - 'simple_form.{error_notification,required}.:'

## Exclude these keys from the `i18n-tasks eq-base' report:
# ignore_eq_base:
#   all:
#     - common.ok
#   fr,es:
#     - common.brand

## Ignore these keys completely:
# ignore:
#  - kaminari.*
