export const REQUEST_IN_PROGRESS = 'REQUEST_IN_PROGRESS';
export const DIAGNOSIS_CONTENT = 'DIAGNOSIS_CONTENT';
export const DIAGNOSIS_ID = 'DIAGNOSIS_ID';
export const QUESTION_SELECTED = 'QUESTION_SELECTED';
export const QUESTION_CONTENT = 'QUESTION_CONTENT';
export const QUESTION_LABEL = 'QUESTION_LABEL';
