export const REQUEST_IN_PROGRESS = 'REQUEST_IN_PROGRESS';
export const DIAGNOSTIC_CONTENT = 'DIAGNOSTIC_CONTENT';
export const DIAGNOSTIC_ID = 'DIAGNOSTIC_ID';
export const QUESTION_SELECTED = 'QUESTION_SELECTED';
export const QUESTION_CONTENT = 'QUESTION_CONTENT';
export const QUESTION_LABEL = 'QUESTION_LABEL';
